title: Md Tamjid Hossain
description: Computer Science Graduate
baseurl: "/resume/"
url: ""
photo_url: "picture.png"

# This is an optional section
# You can skip filling in one or more of the items in this section
email: "tamzidhs@gmail.com"
linkedin: "http://linkedin.com/in/tamjidhossain"
github: "https://github.com/mtamjidhossain"
website: "http://mtamjidhossain.github.io/"
kaggle: "https://www.kaggle.com/mdtamjidhossain"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  
